### ISSUE TITLE
Translate in ConvertTo-LocalFriendlyName fails when it cannot translate a SID and causes Test-TargetResource to fail

### ISSUE THREAD

**Issue by dcrreynolds** [jcwalker/SeceditDsc#2]
Many older images or servers have abandoned SIDs that cannot be translated. When one is found an exception is thrown by translate causing the resource to fail even when actually setting the correct policy.

**Comment by GoateePFE** [comment]
I was just now going to log the same issue. Please add some graceful error handling. SIDs may also come from unreachable trusted domains.

**Comment by jcwalker** [comment]
error handling has been added for this scenario
